[tool.pytest.ini_options]
python_paths = ["yatube_api/"]
DJANGO_SETTINGS_MODULE = "yatube_api.settings"
norecursedirs = ["env/*"]
addopts = "-vv -p no:cacheprovider"
testpaths = ["tests/"]
python_files = ["test_*.py"]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
src_paths = ["yatube_api"]

[tool.flake8]
ignore = ["W503"]
exclude = [
    "tests/",
    "*/migrations/",
    "venv/",
    "env/"
]
per-file-ignores = [
    "*/settings.py: E501",
]
max-line-length = 79
max-complexity = 10
